package nath.dipankar.com;

import com.restfb.Connection;
import com.restfb.DefaultFacebookClient;
import com.restfb.FacebookClient;
import com.restfb.FacebookClient.AccessToken;
import com.restfb.Parameter;
import com.restfb.types.FacebookType;
import com.restfb.types.GraphResponse;
import com.restfb.types.Post;
import com.restfb.types.User;

import javax.swing.*;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import java.util.*;

/**
 *
 * @author Dipankar
 */
public class PostList extends javax.swing.JFrame {
    
    /** Creates new form PostList */
    public PostList() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        bDelete = new javax.swing.JButton();
        cbProList = new javax.swing.JComboBox<>();
        lMessage = new javax.swing.JLabel();
        bLogIn = new javax.swing.JButton();
        postFbText = new javax.swing.JTextField();
        bPost = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PostList");

        jLabel2.setText("Posts Lists With Id's  :");

        bDelete.setText("DELETE");
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });

        cbProList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProListActionPerformed(evt);
            }
        });

        bLogIn.setText("List my posts");
        bLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogInActionPerformed(evt);
            }
        });

        postFbText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postFbTextActionPerformed(evt);
            }
        });

        bPost.setText("POST  IT");
        bPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPostActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(bLogIn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbProList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(bDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                                .addGap(16, 16, 16))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(postFbText, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(bPost, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(bLogIn)
                .addGap(69, 69, 69)
                .addComponent(bDelete)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbProList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addComponent(bPost, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addComponent(postFbText, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    DefaultListModel model = new DefaultListModel();
    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
      
            
            
            String idToDelete = cbProList.getSelectedItem().toString();
            String accessToken="EAACEdEose0cBAKeKPEfGCsKmJAu7Dh1KKvYM1U7ZASqafjZA0n0ZB2PwqZCYbJNyxht4o2pizciWF9UQzYjibwSoPf2tlAZBgl2G4pVevKe531OaNFpccY4rspT5iMM9napMVMQQQqwML8fcr52B5gUsIZB62rVkhHgtQZBZBkwPIhOt4KMtf5XgThpUvEJpCOSJXnaJZAcaPjfxH1iJwTD84BgFHl5pjY70ZD";
            
           // accessToken = accessToken.substring(13,accessToken.lastIndexOf("&"));
            FacebookClient fbClient = new DefaultFacebookClient(accessToken);
            System.out.println(idToDelete);
            Boolean deleted = false;
            try{
                deleted = fbClient.deleteObject(idToDelete);
                cbProList.removeItemAt(cbProList.getSelectedIndex());
            }
            catch(Exception e)
            {
                System.out.println("error while deleting "+e);
            }
            System.out.println("Deleted object? " + deleted);
            System.out.println("ending it");

    }//GEN-LAST:event_bDeleteActionPerformed

    private void cbProListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProListActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_cbProListActionPerformed

    private void bLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogInActionPerformed
        // TODO add your handling code here:
       
        String accessToken="EAACEdEose0cBAKeKPEfGCsKmJAu7Dh1KKvYM1U7ZASqafjZA0n0ZB2PwqZCYbJNyxht4o2pizciWF9UQzYjibwSoPf2tlAZBgl2G4pVevKe531OaNFpccY4rspT5iMM9napMVMQQQqwML8fcr52B5gUsIZB62rVkhHgtQZBZBkwPIhOt4KMtf5XgThpUvEJpCOSJXnaJZAcaPjfxH1iJwTD84BgFHl5pjY70ZD";
        FacebookClient fbClient = new DefaultFacebookClient(accessToken);
        //AccessToken exAccessToken = fbClient.obtainExtendedAccessToken("280189205755590", "2252f789743c1a0dcd28602968d3b640");
        Connection<Post> result = fbClient.fetchConnection("me/posts",Post.class);
        int c=0;
        for (List<Post> res : result)
        {
            if(c==1)
                break;
            c=1;
            for (Post aPost : res)
            {
                cbProList.addItem(aPost.getId());
                System.out.println("nitish fb.com/"+aPost.getId());
            }
        }
        
        
        
        
        
        
        /*String domain = "http://google.com/";
        String appId = "280189205755590";
       
        String authUrl = "https://graph.facebook.com/oauth/authorize?type=user_agent&client_id="+appId+"&redirect_uri="+domain+"&scope=user_about_me,"
                + "user_actions.books,user_actions.fitness,user_actions.music,user_actions.news,user_actions.video,user_birthday,user_education_history,"
                + "user_events,user_photos,user_friends,user_games_activity,user_hometown,user_likes,user_location,user_photos,user_relationship_details,"
                + "user_relationships,user_religion_politics,user_status,user_tagged_places,user_videos,user_website,user_work_history,ads_management,ads_read,email,"
                + "manage_pages,publish_actions,read_insights,read_page_mailboxes,rsvp_event";
       
       
        System.setProperty("webdirver.chrome.driver", "chromedriver.exe");
       
        WebDriver driver = new ChromeDriver();
        driver.get(authUrl);
        String accessToken;
        while(true){
       
            if(!driver.getCurrentUrl().contains("facebook.com")){
            String url = driver.getCurrentUrl();
            accessToken = url.replaceAll(".*#access_token=(.+)&.*", "$1");
           
            driver.quit();
           
                FacebookClient fbClient = new DefaultFacebookClient(accessToken);
                Connection<Post> result = fbClient.fetchConnection("me/feed",Post.class);
                int c=0;
                for (List<Post> res : result) {
                    if(c==1)
                        break;
                    c=1;
                    for (Post aPost : res)
                    {
                        //cbProList.addItem(aPost.getMessage()+" ID= fb.com/"+aPost.getId());
                        System.out.println("nitish fb.com/"+aPost.getId());
                    }
                }
                System.out.println(result);
                //User user = fbClient.fetchObject("me",User.class);
               
               // System.out.println(user.getName());
           
            }
        }*/
       
        
    }//GEN-LAST:event_bLogInActionPerformed

    private void postFbTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postFbTextActionPerformed
       
        
        // TODO add your handling code here:
    }//GEN-LAST:event_postFbTextActionPerformed

    private void bPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPostActionPerformed
      String text = postFbText.getText();
      String accessToken="EAACEdEose0cBAFGK0EjqRVFRpsT6Nlc4rvcP49JDk5uHYxCDlcW2nReA0exDPwa8QmbRgMF1ZA9ZBvm1Cx8ooZAJl2Y2kf1n9kqgzRoC4JVYHexfWXeC89yaveYcyHSeGLAR2t8TglcxX45IoqnIhZChm7gZAENCISqsGKet3dNbFgi5ZBoQarEzjggrI8XXwZD";
      FacebookClient fbClient = new DefaultFacebookClient(accessToken);
     try{
          
         FacebookType publishMessageResponse = fbClient.publish("me/feed", FacebookType.class, Parameter.with(text, "RestFB test"),Parameter.with("link", "http://www.google.com"));

         System.out.println("Published message ID: " + publishMessageResponse.getId());
     }
     catch (Exception e)
     {
         System.out.println("error with  publishiong: "+e);
     }
      
      // TODO add your handling code here:
    }//GEN-LAST:event_bPostActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PostList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PostList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PostList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PostList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PostList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bLogIn;
    private javax.swing.JButton bPost;
    private javax.swing.JComboBox<String> cbProList;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lMessage;
    private javax.swing.JTextField postFbText;
    // End of variables declaration//GEN-END:variables

}
